#!python
"""
GFF processing for wormtable. 

TODO:document.

"""
from __future__ import print_function
from __future__ import division 

import wormtable

def gff_schema_factory(gff_file):
    """
    Returns a schema for the specified GFF file.
    """
    return None 

class GFFTableBuilder(wormtable.TableBuilder):
    """
    Class responsible for parsing a GFF file and creating a table. 
    """
    
    def build(self, gff_file):
        """
        Builds the table.
        """
        self.open_database()
        # do something 
        self.close_database()
        self.finalise()

